export default{
  ADD_USER:'ADD_USER',
  RETRIVE_USER:'RETRIVE_USER',
  DELETE_USER:'DELETE_USER',
  ADD_PARK:'ADD_PARK',
  RETRIVE_PARK:'ADD_RETRIVE',
  DELETE_PARK:'DELETE_PARK',
  LIKE_POST:'LIKE_POST',
  SHARE_POST:'SHARE_POSTs',
  REPORT_POST:'REPORT_POST',
  LOGIN_USER:'LOGIN_USER',
  LOGOUT_USER:'LOGOUT_USER'

}
